.circleci/config.yml
src/app.js

fix(avoid ui): avoid ui audit

---

ui/src/components/SearchBar/index.js
ui/src/features/PerformanceUI/components/JobForm/index.js
ui/src/features/PerformanceUI/instance/configurationColumn.js
ui/src/features/PerformanceUI/instance/get-jobs.js
ui/src/features/PerformanceUI/instance/get-last-reports.js
ui/src/features/PerformanceUI/instance/get-test-reports.js
ui/src/features/PerformanceUI/instance/get-tests.js
ui/src/features/PerformanceUI/instance/redux/action.js
ui/src/features/PerformanceUI/instance/redux/actions/jobsActions.js
ui/src/features/PerformanceUI/instance/redux/reducers/jobsReducer.js
ui/src/features/PerformanceUI/instance/redux/selectors/jobsSelector.js
ui/src/features/PerformanceUI/instance/requestBuilder.js

now you can rerun your job. search by press enter

feat: rerun feature, search by enter

---

ui/src/features/get-tests.js

fix(fix tests sort): fix tests sort

---

ui/src/features/configurationColumn.js

fix(not supported tool tip): not supported tool tip

---

docs/openapi3.yaml

feat(api): add api spec for processors resource

---

docs/devguide/docs/configuration.md
docs/openapi3.yaml
package-lock.json
src/common/consts.js
src/configManager/helpers/configDataMap.js
src/configManager/helpers/convertData.js
src/jobs/models/jobManager.js
tests/integration-tests/configManager/configHandler-test.js
tests/unit-tests/configManager/configHandler-test.js
tests/unit-tests/configManager/helpers/configDataMap-test.js
tests/unit-tests/configManager/helpers/convertData-test.js
ui/src/features/components/ConfigurationForm/index.js

fixes #204 
missing UI (checkbox) @manorlh 
and docs @NivLipetz

Allow insecure TLS

---

docs/devguide/docs/swagger-docs.yaml
docs/openapi3.yaml
src/database/cassandra-handler/init-scripts/14__add_enabled_jobs_table_.cql
src/database/sequlize-handler/migrations/02_jobs_enabled.js
src/jobs/helpers/jobVerifier.js
src/jobs/models/database/cassandra/cassandraConnector.js
src/jobs/models/database/sequelize/sequelizeConnector.js
src/jobs/models/jobManager.js
tests/integration-tests/jobs/createJobGlobal-test.js
tests/integration-tests/jobs/createJobKubernetes-test.js
tests/integration-tests/jobs/updateJob-test.js
tests/unit-tests/jobs/cassandra/cassandra-test.js
tests/unit-tests/jobs/helpers/jobVerifier-test.js
tests/unit-tests/jobs/models/jobManager-test.js
tests/unit-tests/jobs/sequelize/sequelizeConnector-test.js

feat(jobs): add enabled param to jobs

---

docs/openapi3.yaml
src/processors/controllers/processorController.js
src/processors/models/database/cassandra/cassandraConnector.js
src/processors/models/processorsManager.js
src/processors/routes/processorsRoute.js
tests/integration-tests/processors/helpers/requestCreator.js
tests/integration-tests/processors/processors-test.js

feat(custom-js): implement PUT /processors/{processor_id}

---

docs/openapi3.yaml
src/jobs/controllers/jobsController.js
src/jobs/models/docker/jobConnector.js
src/jobs/models/jobManager.js
src/jobs/models/kubernetes/jobConnector.js
src/jobs/models/kubernetes/jobTemplate.js
src/jobs/models/metronome/jobConnector.js
src/jobs/routes/jobsRoute.js
tests/integration-tests/jobs/createJobDocker-test.js
tests/integration-tests/jobs/createJobKubernetes-test.js
tests/integration-tests/jobs/helpers/requestCreator.js
tests/unit-tests/jobs/models/docker/jobConnector-test.js
tests/unit-tests/jobs/models/jobManager-test.js
tests/unit-tests/jobs/models/kubernetes/jobConnector-test.js
tests/unit-tests/jobs/models/metronome/jobConnector-test.js

WIP: Kubernetes Platform - Implement delete all containers #222

---

docs/openapi3.yaml
src/common/consts.js
src/database/cassandra-handler/init-scripts/16__tests_processors_materialized_view.cql
src/processors/models/processorsManager.js
src/tests/models/database.js
src/tests/models/database/cassandra/cassandraConnector.js
src/tests/models/database/sequelize/sequelizeConnector.js
src/tests/models/manager.js
tests/integration-tests/processors/processors-test.js
tests/unit-tests/processors/models/processorsManager-test.js
tests/unit-tests/tests/models/database-test.js
tests/unit-tests/tests/models/manager-test.js

closes #243 
I really struggled with the naming of the function & variable in testsManager and processorManager, if you come up with a better variable name it would be awesome!

fix(processors): prevent user from deleting a processor that a test use

---

src/common/consts.js
src/processors/models/database/sequelize/sequelizeConnector.js
src/tests/helpers/testsVerifier.js
src/tests/routes/testsRoute.js
tests/integration-tests/tests/tests-test.js
tests/testExamples/Test_with_functions.json
tests/unit-tests/processors/sequelize/sequelizeConnector-test.js
tests/unit-tests/tests/helpers/testsVerifier-test.js

feat(processors): verify tests using functions from the processor

---

ui/src/features/components/TestForm/index.js
ui/src/features/components/TestForm/requestOptions.js
ui/src/features/configurationColumn.js

feat(keep-alive): keep-alive

---

Dockerfile

Changes include:
1. Removing the UI source files after the build stage.
2. Upgrading the node interpreter version from `8.4` -> `12.16`

Upgrade and improve docker image

---

.eslintrc.json
docs/openapi3.yaml
package-lock.json
package.json
src/webhooks/controllers/webhooksController.js
src/webhooks/models/database/cassandra/cassandraConnector.js
src/webhooks/models/database/databaseConnector.js
src/webhooks/models/database/sequelize/sequelizeConnector.js
src/webhooks/models/webhookManager.js
src/webhooks/routes/webhooksRouter.js
tests/integration-tests/webhooks/helpers/requestCreator.js
tests/integration-tests/webhooks/webhooks-test.js
tests/unit-tests/jobs/sequelize/sequelizeConnector-test.js
tests/unit-tests/webhooks/sequelize/sequelizeConnector-test.js

feat(webhooks): implement POST /webhooks

---

ui/src/features/components/TestForm/SleepForm.js
ui/src/features/components/TestForm/StepForm.js
ui/src/features/components/TestForm/collapsibleStep.js
ui/src/features/components/TestForm/index.js
ui/src/features/components/TestForm/utils.js

feat(sleep,extra http methods): sleep,extra http methods

---

docs/openapi3.yaml
src/jobs/models/database/sequelize/sequelizeConnector.js
src/webhooks/controllers/webhooksController.js
src/webhooks/models/database/databaseConnector.js
src/webhooks/models/database/sequelize/sequelizeConnector.js
src/webhooks/models/webhookManager.js
src/webhooks/routes/webhooksRouter.js
tests/integration-tests/webhooks/helpers/requestCreator.js
tests/integration-tests/webhooks/webhooks-test.js
tests/unit-tests/webhooks/sequelize/sequelizeConnector-test.js

implement DELETE /webhooks/:webhook_id

---

src/common/generateError.js
src/processors/models/processorsManager.js
src/webhooks/controllers/webhooksController.js
src/webhooks/models/database/cassandra/cassandraConnector.js
src/webhooks/models/database/databaseConnector.js
src/webhooks/models/database/sequelize/sequelizeConnector.js
src/webhooks/models/webhookManager.js
src/webhooks/routes/webhooksRouter.js
tests/integration-tests/webhooks/helpers/requestCreator.js
tests/integration-tests/webhooks/webhooks-test.js

implement PUT /webhooks/:webhook_id

---

ui/src/features/configurationColumn.js

fix(notes render bug): notes render bug

---

package-lock.json
ui/src/components/Input/index.js
ui/src/components/Tabs/Tabs.js
ui/src/features/components/TestForm/BodyEditor.js
ui/src/features/components/TestForm/collapsibleStep.js
ui/src/features/components/TestForm/utils.js
ui/src/features/get-tests.js

feat(ui-step-name): ui-step-name

---

docs/devguide/docs/swagger-docs.yaml
docs/openapi3.yaml
package-lock.json
package.json
tests/docs/openapi-test.js

| Tests added     | ✔                                                                        |
Further  information: …

fix(openapi): fixed missing schema key

---

src/server.js

feat(server): verify INTERNAL_ADDRESS is reachable and correct

---

src/common/generateError.js

refactor(common): fixed typo

---

src/jobs/models/jobManager.js
ui/src/features/components/JobForm/index.js
ui/src/features/requestBuilder.js

| Bug fix         | ✔                                                                       |

fix(ui): revert environment

---

setup-env.js

Adding .env file for the ui folder
This is mainly useful for windows users.

chore(local-setup): setup .env file for the ui folder

---

package-lock.json
package.json
src/jobs/helpers/jobVerifier.js
tests/integration-tests/jobs/updateJob-test.js
tests/unit-tests/jobs/helpers/jobVerifier-test.js
ui/package-lock.json
ui/package.json
ui/src/features/components/JobForm/index.js
ui/src/features/components/JobForm/validator.js

| Tests added     | ✔                                                                       |
Related issues: #454 …

fix: add cron validation to jobVerifier

---

ui/src/features/components/TestForm/collapsibleStep.js
ui/src/features/components/TestForm/index.js
ui/src/features/components/TestForm/stepsList.js

ui-fix-collapsible-on-edit-test
Closes #XXX , #XXX ...

fix(ui-fix-collapsible-on-edit-test): ui-fix-collapsible-on-edit-test

---

ui/src/features/components/TestForm/index.js

This will resolve issue #470.
Hi guys, I've removed the Cancel button and replaced the other two with icons. Let me know what you think!

chore(ui): replaced buttons with icons on create test form (#470)

---

ui/src/features/components/TestForm/index.js

ui-sticky-test-form-actions
| Tests added     | ✔/✖ …

feat(ui-sticky-test-form-actions): ui-sticky-test-form-actions

---

ui/src/features/components/JobForm/index.js
ui/src/features/components/JobForm/utils.js
ui/src/features/get-jobs.js

revert(fix-edit-job): fix-edit-job

---

ui/src/features/components/JobForm/index.js

fix(ui-fix-edit-job): ui-fix-edit-job

---

ui/src/features/components/TestForm/JSEditor.js
ui/src/features/components/TestForm/StepForm.js
ui/src/features/components/TestForm/addScenarioForm.js
ui/src/features/components/TestForm/collapsibleScenarioConfig.js
ui/src/features/components/TestForm/collapsibleStep.js

new tab in step/scenario screen that opens JS editor, currently without backend functionality
Closes #465

feat(ui): add custom js editor in create test screen (#465)

---

ui/src/features/components/Report/index.js

ui-fix-loading-report
Closes #XXX , #XXX ...
Further  information:

feat(ui-fix-loading-report): ui-fix-loading-report

---

ui/src/features/get-last-reports.js
ui/src/features/get-test-reports.js

fix(reports): show all reports when favorites toggle is off

---

ui/src/features/components/Report/index.js

Closes #XXX , #XXX ...
Further  information:

Fix loading report

---

ui/src/features/components/TestForm/index.js
ui/src/validators/validate-urls.js

fix(ui-fix-edit-test): ui-fix-edit-test

---

package-lock.json

fix: vulnerabilities

---

src/database/sequlize-handler/migrations/12_reports_benchmarks.js

fix: add report benchmark data to database migration scripts

---

src/reports/models/notifier.js
src/streaming/entities/resource.js
tests/integration-tests-with-streaming/dockerFullFlow-test.js

| New feature     | ✔                                                                       |
| Tests added     | ✔                                                                   |

fix: produce test's benchmark data when exists

---

Dockerfile
package-lock.json
package.json
ui/package.json

Reduce docker image size

---

package-lock.json
package.json

fix: update sqlite

---

ui/src/components/TitleInput/index.js
ui/src/features/components/TestForm/BodyEditor.js
ui/src/features/components/TestForm/addScenarioForm.js
ui/src/features/components/TestForm/additionalInfo.js
ui/src/features/components/TestForm/utils.js

refactor: support additional information for artillery tests

---

.circleci/config.yml
package-lock.json
ui/src/App/common/env.js

Support additional info UI

---

src/chaos-experiments/models/database/databaseConnector.js
src/chaos-experiments/models/database/sequelize/sequelizeConnector.js
src/database/sequlize-handler/consts.js
tests/unit-tests/chaos-experiments/sequelize/sequelizeConnector-test.js

| Bug fix         ✖                                                                        |
| New feature     | ✔                                                                      |
| Breaking change |✖                                                                        |
| Tests added     |✔                                                                        |
Related issues: #634 …

feat: add chaos job experiments to db

---

src/chaos-experiments/models/database/databaseConnector.js
src/chaos-experiments/models/database/sequelize/sequelizeConnector.js
src/jobs/models/jobExperimentsHandler.js
src/jobs/models/jobManager.js
tests/unit-tests/chaos-experiments/models/chaosExperimentsManager-test.js
tests/unit-tests/jobs/models/jobExperimentsHandler-test.js

feat: create job experiments on createJob logics

---

src/database/sequlize-handler/migrations/13_jobs_experiment.js

| New feature     | ✔                                                                     |
| Documentation   |✖                                                                        |
Related issues: #634

fix: Alter jobs script to add experiments column

---

src/chaos-experiments/models/database/sequelize/sequelizeConnector.js
src/reports/models/aggregateReportManager.js

| New feature     | ✔                                                                    |
| Breaking change |✖                                                                        |
| Tests added     | ✔                                                                   |
Related issues: #634

feat: Aggregate report experiments

---

src/app.js
src/chaos-experiments/models/chaosExperimentsManager.js
src/jobs/models/jobManager.js
src/jobs/models/kubernetes/jobConnector.js
src/jobs/models/kubernetes/jobExperimentsHandler.js
tests/unit-tests/jobs/models/jobExperimentsHandler-test.js
tests/unit-tests/jobs/models/jobManager-test.js
tests/unit-tests/jobs/models/kubernetes/jobConnector-test.js
tests/unit-tests/k8sChaosExperiments/models/chaosExperimentsManager-test.js

| Bug fix         | ✔✖                                                                        |
| New feature     | ✖                                                                      |
| Breaking change |✖                                                                        |
Related issues: #XXX , …

refactor: Chaos structure refactor

---

src/chaos-experiments/models/chaosExperimentsManager.js
src/common/consts.js
src/jobs/models/kubernetes/jobExperimentsHandler.js
tests/unit-tests/jobs/models/jobExperimentsHandler-test.js
tests/unit-tests/k8sChaosExperiments/models/chaosExperimentsManager-test.js

| New feature     | ✖                                                              |
| Tests added     | ✔                                                                   | …

feat: add custom label to experiment crd

---

tests/integration-tests/tests/tests-test.js
ui/src/features/components/Report/Charts.js
ui/src/features/components/Report/index.js
ui/src/features/redux/selectors/reportsSelector.js

Support experiments in graphs
| New feature     | ✔                                                                   |
| Tests added     | ✖ …

Visualize experiments graph

---

ui/src/features/components/Report/Charts.js
ui/src/features/components/Report/index.js
ui/src/features/redux/selectors/reportsSelector.js

| New feature     | ✔                                                                      |
| Deprecations    | ✖                                                                     |
| Documentation   |✖                                                                        |
| Tests added     | ✖                                                                         |
Related issues: #XXX , …

feat: Visualize experiments graph

---

ui/package-lock.json
ui/package.json
ui/src/App/index.js
ui/src/constants.js
ui/src/features/components/JobForm/index.js
ui/src/features/components/Report/Charts.js
ui/src/features/get-configuration.js
ui/src/features/get-jobs.js
ui/src/features/get-tests.js
ui/src/features/mainMenu.js

| New feature     | ✔                                                                        |
Related issues: #XXX …

feat: Hide chaos ui components when not runinng on k8s

---

src/chaos-experiments/models/chaosExperimentsManager.js
src/chaos-experiments/models/kubernetes/chaosExperimentConnector.js
src/jobs/models/kubernetes/jobConnector.js
src/jobs/models/kubernetes/jobExperimentsHandler.js
tests/unit-tests/jobs/models/jobExperimentsHandler-test.js
tests/unit-tests/jobs/models/kubernetes/jobConnector-test.js
tests/unit-tests/k8sChaosExperiments/models/chaosExperimentsManager-test.js
tests/unit-tests/k8sChaosExperiments/models/kubernetes/chaosExperimentConnector-test.js

feat: stop experiments on stop job

---

src/reports/models/reportsManager.js
tests/integration-tests/reports/reportsApi-test.js
tests/unit-tests/reporter/models/reportsManager-test.js

| New feature     | ✔                                                                        |
Related issues: #XXX …

feat: Get reports includes experiments

---

ui/src/features/components/JobForm/index.js
ui/src/features/components/JobForm/utils.js
ui/src/features/get-last-reports.js
ui/src/features/get-test-reports.js

| New feature     | ✔                                                                      |
| Deprecations    |✖                                                                        |
Related issues: #XXX , …

feat: Rerun with experiments

---

docs/openapi3.yaml
src/app.js
src/common/consts.js
src/configManager/helpers/configDataMap.js
src/jobs/models/jobManager.js
src/jobs/models/kubernetes/jobConnector.js
src/reports/models/reportsManager.js
tests/configurations/kubernetesConfiguration.sh
tests/integration-tests/chaos-experiments/chaos-experiments-context-test.js
tests/integration-tests/configManager/configHandler-test.js
tests/integration-tests/run.sh
tests/integration-tests/testUtils.js
tests/unit-tests/configManager/configHandler-test.js
tests/unit-tests/configManager/helpers/configDataMap-test.js
tests/unit-tests/jobs/models/kubernetes/jobConnector-test.js
tests/unit-tests/reporter/models/reportsManager-test.js

feat: feature toggle on chaos experiments

---

tests/integration-tests/chaos-experiments/helpers/requestCreator.js
tests/integration-tests/jobs/createJobKubernetes-test.js

fix: add integration tests

---

ui/src/App/index.js
ui/src/constants.js
ui/src/features/components/JobForm/index.js
ui/src/features/get-jobs.js
ui/src/features/get-tests.js
ui/src/features/mainMenu.js

| New feature     | ✔                                                                     |
| Documentation   |✖                                                                        |
Related issues: #XXX , …

feat: ui feature toggle chaos

---

tests/integration-tests/chaos-experiments/helpers/requestCreator.js
tests/integration-tests/jobs/createJobKubernetes-test.js

fix: add Negative integration tests

---

.circleci/config.yml
src/chaos-experiments/controllers/chaosExperimentController.js
src/chaos-experiments/models/chaosExperimentsManager.js
src/chaos-experiments/models/kubernetes/chaosExperimentConnector.js
src/jobs/models/jobManager.js
tests/integration-tests/chaos-experiments/helpers/requestCreator.js
tests/integration-tests/jobs/createJobKubernetes-test.js
tests/unit-tests/k8sChaosExperiments/models/chaosExperimentsManager-test.js

fix: fb code review remarks

---

tests/configurations/dockerRun.sh

Closes #XXX , #XXX ...
Further  information:

fix: remove platform from mysql docker init

---

.circleci/config.yml

| New feature      | ✖                                                                         |
| Breaking change | ✖                                                                          |
| Deprecations    | ✖                                                                          |
| Documentation  | ✖                                                                           |
| Tests added     | ✖                                                                          |

ci: fix fingerprint
